name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a v3

      - name: Make test scripts executable
        run: chmod +x ./test*.sh  # Cambia permisos de los scripts

  test:
    runs-on: ubuntu-latest
    needs: build  # Asegúrate de que el trabajo de build se complete primero

    strategy:
      matrix:
        test: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Actualizado a v3

      - name: Run tests
        run: ./test${{ matrix.test }}.sh  # Ejecuta los scripts de prueba
