name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make test scripts executable
        run: |
          chmod +x ./test1.sh
          chmod +x ./test2.sh
          chmod +x ./test3.sh

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        test: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./test${{ matrix.test }}.sh
