name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_file: [test1.sh, test2.sh, test3.sh]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permissions for test scripts
        run: chmod +x ./tests/*.sh

      - name: Check file type
        run: file ./tests/${{ matrix.test_file }}

      - name: Run tests in parallel
        run: bash ./tests/${{ matrix.test_file }}
