name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Especifica la versión de Node.js que necesitas



      - name: Make test scripts executable
        run: chmod +x ./test*.sh

      - name: List permissions of test scripts
        run: ls -l ./test*.sh

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        test: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Especifica la versión de Node.js que necesitas

      - name: List permissions of test scripts
        run: ls -l ./test*.sh

      - name: Run tests
        run: ./test${{ matrix.test }}.sh
