name: CI/CD_Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make test scripts executable
        run: chmod +x ./test*.sh

  test:
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        test: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: ./test${{ matrix.test }}.sh

